ALTER TABLE users ADD COLUMN Reset_Token VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN Reset_Token_Expiry DATETIME NULL;
ALTER TABLE users ADD COLUMN Profile_Photo LONGTEXT NULL;
ALTER TABLE users ADD COLUMN New_Email VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN Email_Verify_Token VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN Email_Verify_Token_Expiry DATETIME NULL;
ALTER TABLE users ADD COLUMN Phone VARCHAR(20) NULL;
