ALTER TABLE schedules ADD COLUMN Academic_Year VARCHAR(15) DEFAULT '2025-2026';
ALTER TABLE schedules ADD COLUMN Semester VARCHAR(20) DEFAULT '1st Semester';
ALTER TABLE schedules ADD COLUMN Color_Theme VARCHAR(50) NULL;
